//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKaraoke
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_HOA_DON_NHAP
    {
        public long IDHoaDonNhap { get; set; }
        public int IDMatHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGiaNhap { get; set; }
    
        public virtual HOA_DON_NHAP HOA_DON_NHAP { get; set; }
        public virtual MAT_HANG MAT_HANG { get; set; }
    }
}
