//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKaraoke
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON_BAN_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON_BAN_HANG()
        {
            this.CHI_TIET_HOA_DON_BAN = new HashSet<CHI_TIET_HOA_DON_BAN>();
        }
    
        public long IDHoaDonBanHang { get; set; }
        public string IDPhong { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public Nullable<int> DonGiaPhong { get; set; }
        public string NguoiBan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_HOA_DON_BAN> CHI_TIET_HOA_DON_BAN { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
